# Generated by Django 3.2.5 on 2021-07-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
